### ISSUE TITLE
cannot fetch unsupported input '{"type":"file","url":"https://block.energized.pro/extensions/regional/formats/hosts"}'

### ISSUE THREAD

**Issue by yoctocell** [eadwu/flakes#1]
I am trying to use the `sourcehut` module from the `custom` branch and I have put

```nix
eadwu-flakes.url = "github:eadwu/flakes/custom";
```

 in my `flake.nix`. When I do `nixos-rebuild switch` I get an error saying

```
cannot fetch unsupported input '{"type":"file","url":"https://block.energized.pro/extensions/regional/formats/hosts"}'
```

Here is my nix version.

```sh
$ nix --version
nix (Nix) 2.4pre20201102_550e11f
```

Any ideas on how to solve this?

**Comment by eadwu** [comment]
Copy the specific module files themselves is probably the best option.

File input isn't officially supported but I'm using a custom derivation so it doesn't really matter on my end.

**Comment by yoctocell** [comment]
Ok, thanks for the clarification!
